/**
 * Export Report Utility
 * Generates comprehensive reports from chat conversations and document analysis
 */

import { ChatMessage, ProcessedDocument, ExtractedBenefit } from './types';

export interface ExportOptions {
  format: 'json' | 'markdown' | 'html' | 'txt';
  includeMetadata?: boolean;
  includeBenefits?: boolean;
  includeCitations?: boolean;
  includeTimestamps?: boolean;
}

export interface ExportReport {
  generatedAt: string;
  documentInfo?: {
    name: string;
    filename: string;
    pageCount: number;
    uploadedAt: string;
    benefitsCount: number;
    sectionsCount: number;
  };
  conversation: Array<{
    role: string;
    content: string;
    timestamp?: string;
    citations?: Array<{
      sectionNumber: string;
      sectionTitle: string;
      excerpt: string;
      pageNumber: number;
    }>;
  }>;
  benefits?: ExtractedBenefit[];
  summary?: string;
}

/**
 * Generate export report from chat messages and document
 */
export function generateReport(
  messages: ChatMessage[],
  document: ProcessedDocument | null,
  options: ExportOptions = { format: 'json' }
): ExportReport {
  const report: ExportReport = {
    generatedAt: new Date().toISOString(),
    conversation: messages
      .filter(msg => msg.id !== 'welcome') // Exclude welcome message
      .map(msg => ({
        role: msg.role,
        content: msg.content,
        ...(options.includeTimestamps && { timestamp: msg.timestamp.toISOString() }),
        ...(options.includeCitations && msg.citations && { citations: msg.citations }),
      })),
  };

  if (document && options.includeMetadata) {
    report.documentInfo = {
      name: document.name,
      filename: document.filename,
      pageCount: document.pageCount,
      uploadedAt: document.uploadedAt.toISOString(),
      benefitsCount: document.benefits?.length || 0,
      sectionsCount: document.sections?.length || 0,
    };
  }

  if (document && options.includeBenefits) {
    report.benefits = document.benefits;
  }

  if (document) {
    report.summary = document.summary;
  }

  return report;
}

/**
 * Format report as JSON
 */
export function formatAsJSON(report: ExportReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Format report as Markdown
 */
export function formatAsMarkdown(report: ExportReport): string {
  let markdown = `# IBM Bob Report\n\n`;
  markdown += `**Generated:** ${new Date(report.generatedAt).toLocaleString()}\n\n`;

  if (report.documentInfo) {
    markdown += `## Document Information\n\n`;
    markdown += `- **Name:** ${report.documentInfo.name}\n`;
    markdown += `- **Filename:** ${report.documentInfo.filename}\n`;
    markdown += `- **Pages:** ${report.documentInfo.pageCount}\n`;
    markdown += `- **Uploaded:** ${new Date(report.documentInfo.uploadedAt).toLocaleString()}\n`;
    markdown += `- **Benefits Found:** ${report.documentInfo.benefitsCount}\n`;
    markdown += `- **Sections:** ${report.documentInfo.sectionsCount}\n\n`;
  }

  if (report.summary) {
    markdown += `## Document Summary\n\n${report.summary}\n\n`;
  }

  if (report.benefits && report.benefits.length > 0) {
    markdown += `## Extracted Benefits\n\n`;
    report.benefits.forEach((benefit, index) => {
      markdown += `### ${index + 1}. ${benefit.title}\n\n`;
      markdown += `- **Category:** ${benefit.category}\n`;
      markdown += `- **Value:** ${benefit.exactValue}\n`;
      markdown += `- **Description:** ${benefit.description}\n`;
      if (benefit.conditions.length > 0) {
        markdown += `- **Conditions:**\n`;
        benefit.conditions.forEach(condition => {
          markdown += `  - ${condition}\n`;
        });
      }
      markdown += `- **Reference:** ${benefit.sectionRef} (Page ${benefit.pageNumber})\n`;
      markdown += `- **Confidence:** ${benefit.confidence}\n\n`;
    });
  }

  markdown += `## Conversation History\n\n`;
  report.conversation.forEach((msg, index) => {
    const role = msg.role === 'user' ? '👤 User' : '🤖 Assistant';
    markdown += `### ${role}${msg.timestamp ? ` - ${new Date(msg.timestamp).toLocaleString()}` : ''}\n\n`;
    markdown += `${msg.content}\n\n`;
    
    if (msg.citations && msg.citations.length > 0) {
      markdown += `**Citations:**\n`;
      msg.citations.forEach(citation => {
        markdown += `- ${citation.sectionNumber} - ${citation.sectionTitle} (Page ${citation.pageNumber})\n`;
        markdown += `  > ${citation.excerpt}\n`;
      });
      markdown += `\n`;
    }
  });

  markdown += `\n---\n*Report generated by IBM Bob*\n`;
  return markdown;
}

/**
 * Format report as HTML
 */
export function formatAsHTML(report: ExportReport): string {
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>IBM Bob Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      max-width: 900px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .container {
      background: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 { color: #1a73e8; border-bottom: 3px solid #1a73e8; padding-bottom: 10px; }
    h2 { color: #333; margin-top: 30px; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }
    h3 { color: #555; margin-top: 20px; }
    .metadata { background: #f8f9fa; padding: 15px; border-radius: 4px; margin: 20px 0; }
    .metadata p { margin: 5px 0; }
    .benefit-card {
      background: #f8f9fa;
      border-left: 4px solid #1a73e8;
      padding: 15px;
      margin: 15px 0;
      border-radius: 4px;
    }
    .message {
      margin: 20px 0;
      padding: 15px;
      border-radius: 8px;
    }
    .user-message {
      background: #e3f2fd;
      border-left: 4px solid #2196f3;
    }
    .assistant-message {
      background: #f1f8e9;
      border-left: 4px solid #8bc34a;
    }
    .citation {
      background: #fff3e0;
      padding: 10px;
      margin: 10px 0;
      border-left: 3px solid #ff9800;
      font-size: 0.9em;
    }
    .timestamp {
      color: #666;
      font-size: 0.85em;
      margin-bottom: 8px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      color: #666;
      font-size: 0.9em;
    }
    ul { padding-left: 20px; }
    li { margin: 5px 0; }
  </style>
</head>
<body>
  <div class="container">
    <h1>📊 IBM Bob Report</h1>
    <p class="timestamp"><strong>Generated:</strong> ${new Date(report.generatedAt).toLocaleString()}</p>
`;

  if (report.documentInfo) {
    html += `
    <div class="metadata">
      <h2>📄 Document Information</h2>
      <p><strong>Name:</strong> ${report.documentInfo.name}</p>
      <p><strong>Filename:</strong> ${report.documentInfo.filename}</p>
      <p><strong>Pages:</strong> ${report.documentInfo.pageCount}</p>
      <p><strong>Uploaded:</strong> ${new Date(report.documentInfo.uploadedAt).toLocaleString()}</p>
      <p><strong>Benefits Found:</strong> ${report.documentInfo.benefitsCount}</p>
      <p><strong>Sections:</strong> ${report.documentInfo.sectionsCount}</p>
    </div>
`;
  }

  if (report.summary) {
    html += `
    <h2>📝 Document Summary</h2>
    <p>${report.summary}</p>
`;
  }

  if (report.benefits && report.benefits.length > 0) {
    html += `<h2>🎁 Extracted Benefits</h2>`;
    report.benefits.forEach((benefit, index) => {
      html += `
      <div class="benefit-card">
        <h3>${index + 1}. ${benefit.title}</h3>
        <p><strong>Category:</strong> ${benefit.category}</p>
        <p><strong>Value:</strong> ${benefit.exactValue}</p>
        <p><strong>Description:</strong> ${benefit.description}</p>
`;
      if (benefit.conditions.length > 0) {
        html += `<p><strong>Conditions:</strong></p><ul>`;
        benefit.conditions.forEach(condition => {
          html += `<li>${condition}</li>`;
        });
        html += `</ul>`;
      }
      html += `
        <p><strong>Reference:</strong> ${benefit.sectionRef} (Page ${benefit.pageNumber})</p>
        <p><strong>Confidence:</strong> ${benefit.confidence}</p>
      </div>
`;
    });
  }

  html += `<h2>💬 Conversation History</h2>`;
  report.conversation.forEach((msg) => {
    const messageClass = msg.role === 'user' ? 'user-message' : 'assistant-message';
    const roleIcon = msg.role === 'user' ? '👤' : '🤖';
    const roleName = msg.role === 'user' ? 'User' : 'Assistant';
    
    html += `
    <div class="message ${messageClass}">
      <div class="timestamp">${roleIcon} <strong>${roleName}</strong>${msg.timestamp ? ` - ${new Date(msg.timestamp).toLocaleString()}` : ''}</div>
      <p>${msg.content.replace(/\n/g, '<br>')}</p>
`;
    
    if (msg.citations && msg.citations.length > 0) {
      html += `<p><strong>Citations:</strong></p>`;
      msg.citations.forEach(citation => {
        html += `
        <div class="citation">
          <strong>${citation.sectionNumber} - ${citation.sectionTitle}</strong> (Page ${citation.pageNumber})<br>
          <em>${citation.excerpt}</em>
        </div>
`;
      });
    }
    html += `</div>`;
  });

  html += `
    <div class="footer">
      <p>Report generated by <strong>IBM Bob</strong></p>
    </div>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Format report as plain text
 */
export function formatAsText(report: ExportReport): string {
  let text = `IBM BOB REPORT\n`;
  text += `${'='.repeat(80)}\n\n`;
  text += `Generated: ${new Date(report.generatedAt).toLocaleString()}\n\n`;

  if (report.documentInfo) {
    text += `DOCUMENT INFORMATION\n`;
    text += `${'-'.repeat(80)}\n`;
    text += `Name: ${report.documentInfo.name}\n`;
    text += `Filename: ${report.documentInfo.filename}\n`;
    text += `Pages: ${report.documentInfo.pageCount}\n`;
    text += `Uploaded: ${new Date(report.documentInfo.uploadedAt).toLocaleString()}\n`;
    text += `Benefits Found: ${report.documentInfo.benefitsCount}\n`;
    text += `Sections: ${report.documentInfo.sectionsCount}\n\n`;
  }

  if (report.summary) {
    text += `DOCUMENT SUMMARY\n`;
    text += `${'-'.repeat(80)}\n`;
    text += `${report.summary}\n\n`;
  }

  if (report.benefits && report.benefits.length > 0) {
    text += `EXTRACTED BENEFITS\n`;
    text += `${'-'.repeat(80)}\n\n`;
    report.benefits.forEach((benefit, index) => {
      text += `${index + 1}. ${benefit.title}\n`;
      text += `   Category: ${benefit.category}\n`;
      text += `   Value: ${benefit.exactValue}\n`;
      text += `   Description: ${benefit.description}\n`;
      if (benefit.conditions.length > 0) {
        text += `   Conditions:\n`;
        benefit.conditions.forEach(condition => {
          text += `     - ${condition}\n`;
        });
      }
      text += `   Reference: ${benefit.sectionRef} (Page ${benefit.pageNumber})\n`;
      text += `   Confidence: ${benefit.confidence}\n\n`;
    });
  }

  text += `CONVERSATION HISTORY\n`;
  text += `${'-'.repeat(80)}\n\n`;
  report.conversation.forEach((msg) => {
    const role = msg.role === 'user' ? 'USER' : 'ASSISTANT';
    text += `[${role}]${msg.timestamp ? ` - ${new Date(msg.timestamp).toLocaleString()}` : ''}\n`;
    text += `${msg.content}\n`;
    
    if (msg.citations && msg.citations.length > 0) {
      text += `\nCitations:\n`;
      msg.citations.forEach(citation => {
        text += `  - ${citation.sectionNumber} - ${citation.sectionTitle} (Page ${citation.pageNumber})\n`;
        text += `    "${citation.excerpt}"\n`;
      });
    }
    text += `\n${'-'.repeat(80)}\n\n`;
  });

  text += `Report generated by IBM Bob\n`;
  return text;
}

/**
 * Export report in specified format
 */
export function exportReport(
  messages: ChatMessage[],
  document: ProcessedDocument | null,
  options: ExportOptions
): string {
  const report = generateReport(messages, document, {
    ...options,
    includeMetadata: options.includeMetadata ?? true,
    includeBenefits: options.includeBenefits ?? true,
    includeCitations: options.includeCitations ?? true,
    includeTimestamps: options.includeTimestamps ?? true,
  });

  switch (options.format) {
    case 'json':
      return formatAsJSON(report);
    case 'markdown':
      return formatAsMarkdown(report);
    case 'html':
      return formatAsHTML(report);
    case 'txt':
      return formatAsText(report);
    default:
      return formatAsJSON(report);
  }
}

/**
 * Download report as file
 */
export function downloadReport(
  content: string,
  format: 'json' | 'markdown' | 'html' | 'txt',
  filename?: string
): void {
  const mimeTypes = {
    json: 'application/json',
    markdown: 'text/markdown',
    html: 'text/html',
    txt: 'text/plain',
  };

  const extensions = {
    json: 'json',
    markdown: 'md',
    html: 'html',
    txt: 'txt',
  };

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const defaultFilename = `ibm-bob-report-${timestamp}.${extensions[format]}`;
  
  const blob = new Blob([content], { type: mimeTypes[format] });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || defaultFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Made with Bob